

run_name: "Overfitting_run_e2e"
neptune_api: ""
neptune_project: ""
data_path: "/Users/lucasvilsen/Documents/Documents/DL-CausalSpeechProject/sample_ears_wham"

debug:
  test_run: true
  save_memory: true # Save memory if you have low memory available (< 16GB)
  overfit_run: true

training_init:
  teacher_path: "" # Leave empty to init from scratch
  student_path: "" # Leave empty to init from scratch
  train_teacher: true
  train_student: false
  train_student_without_teacher: false

training_params:
  lr: 0.001
  dropout: 0.0
  weight_decay: 0.0
  epochs: 200
  epoch_to_turn_off_intermediate: 0
  batch_size: 1
  teacher_predictions_factor: 0.5 # 1 = Only teacher, 0 = Only labels
