

run_name: "train_teacher"
neptune_api: ""
neptune_project: ""
data_path: ""

debug:
  test_run: false
  save_memory: false # Save memory if you have low memory available
  overfit_run: false

training_init:
  teacher_path: "models/teacher_full_training.pth" # Leave empty to init from scratch
  student_path: "" # Leave empty to init from scratch
  train_teacher: true
  train_student: false
  train_student_without_teacher: false

training_params:
  lr: 0.001
  dropout: 0.0 # Does not work
  weight_decay: 0.0 # Does not work
  epochs: 200
  epoch_to_turn_off_intermediate: 0 # Does not work
  batch_size: 1
  teacher_predictions_factor: 0.5 # 1 = Only teacher, 0 = Only labels
